---
title: "Week-4-Programming-Assignment"
author: "Dean Basic"
date: "2022-09-08"
output: html_document
---

# Week 4 R Programming Coursera Assignment   

Information file [here](https://d3c33hcgiwev3.cloudfront.net/_2a0d228f9a48b3de85eedf022225fac9_ProgAssignment3.pdf?Expires=1662681600&Signature=LJFs-eAxHnWi3rcnNru4Y7Med7K3yEE8Gg5eOwgmpTXjFil00w8XyBWPxkho8xCZa7ANrxHjw~2Q-tRQroeHQtbVYowzo6PXHP1gaq00iG-7kIDuj1DKqd3vuTSdzifuUPm55j3VY56tz0gjIxkH2K9AHWDQ3hTkOaDoxFFcebc_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A) in pdf.   

## Basic Data Loading 

`hospital <- read.csv("hospital-data.csv")`   

Perform a basic summary   
```
ncol(hospital) 
colnames(hospital)
dim(hospital)
str(hospital)
head(hospital)
```    
\
`outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")`    


## 2. Finding the best hospital in a state 

*"Write a function called best that take two arguments: the 2-character abbreviated name of a state and an outcome name. The function reads the outcome-of-care-measures.csv file and returns a character vector with the name of the hospital that has the best (i.e. lowest) 30-day mortality for the specified outcome in that state. The hospital name is the name provided in the Hospital.Name variable. The outcomes can be one of “heart attack”, “heart failure”, or “pneumonia”. Hospitals that do not have data on a particular outcome should be excluded from the set of hospitals when deciding the rankings."*

**If there is a tie for the best hospital for a given outcome, then the hospital names should be sorted in alphabetical order and the first hospital in that set should be chosen (i.e. if hospitals “b”, “c”, and “f” are tied for best, then hospital “b” should be returned).**   

I must admit, with the various if-else statements, this has turned out to be clunkier and dirtier than I'd like - much can be improved and shortened had I the additional knowledge.. For now it must do though. 


```   
best <- function(state, outcome = c("heart attack","heart failure","pneumonia")){
    
    data <- data.frame() # create open dataframe 
    
    ## Read outcome data 
    outcomes <- read.csv("outcome-of-care-measures.csv", colClasses =              "character"
     ,na.string = "Not Available") 
     
    ## Make list of unique state values 
    uniquestate <- as.list(unique(outcomes$State))
    
    ## Check that state and outcome are valid 
    if (state %in% uniquestate){
    paste("proceed")
    }  
    else {
    stop("invalid state") # cancel execution and print error message
    }

    ## Return hospital name in that state with lowest 30-day death
    
    data <- outcomes[, c(2, 7, 23)] # subset the data frame with columns of        interest # 17 for heart failure, 23 for pnemonia
    data2 <- na.omit(data) # omit the NA values
    data2[,3] <- as.numeric(data2[,3]) # convert the char column to numeric
    data2 <- data2[data2[, 2] == state ,] # subset data frame with state values
    
    min <- min(data2[, 3]) # find the minimum value in the given column 
    
    data3 <- data2[data2[, 3] == min ,] # subset the data frame to contain only #those values 
    #equivalent to min
    sort(data3[, 1]) # sort the output alphabetically 
}

```   

as for the information of heart attack etc, we can do this with a series of if 
else - else if statements.   


Hospital.30.Day.Death..Mortality..Rates.from.Heart.Fai     lure


# 3. Ranking hospitals by outcome in a state 

Write a function called rankhospital that takes three arguments: the 2-character abbreviated name of a state (state), an outcome (outcome), and the ranking of a hospital in that state for that outcome (num). The function reads the outcome-of-care-measures.csv file and returns a character vector with the name of the hospital that has the ranking specified by the num argument.   




## Sample play code 

Create a mock data frame

`data <- data.frame(state = c("TX", "AZ", "ZD", "ED", "TS", "NY"), morality = c(10.2, 11.2, 14, 13.2, 8.2, 8.2))`    

Test out the rankings - one must first sort, and then order the sorted, putting the values in a new column 
`data$rank <- order(sort(data$morality, decreasing = TRUE))`


Information for the data file that will be used will come from the 19. Outcome of Case Measures. We want 1) the name of the hospital in col2, 2) the state in col7, 3) heart attack outcomes in col11, 4) heart failure outcomes in col17 and 4) pneumonia outcomes in col23.       

### Final code 

```   
rankhospital <- function(state, outcome, num = as.list(...)){
    
    # Load all information into the data frame
    
    outcomes <- read.csv("outcome-of-care-measures.csv", colClasses =                      "character", na.string = "Not Available")[, c(2,7,11,17,23)]  
    # Change column names 
    colnames(outcomes) <- c("Hospital-Name", "State", "heart attack",                         "heart failure", "pneumonia")    
        
    ## Make list of unique state values 
    uniquestate <- as.list(unique(outcomes$State))
    
    ## Check that state and outcome are valid 
    if (state %in% uniquestate){
        paste("proceed")
    }  
    else {
    stop("invalid state") # cancel execution and print error message
    }  

    # Form data frame from provided state value 
    stateout <- outcomes[outcomes$State == state, ]
    # Subset dataset from provided outcome 
    healthout <- subset(stateout, select = c("Hospital-Name", outcome)) 

    # Remove NA values and then sort and rank 
    healthout <- na.omit(healthout)

    # Determine number of rows in the data frame after sorting and ranking 
    #rows <- nrow(unique(healthout$outcome) 
    
    # unique on rate - the last value will by default by the first duplicate if     # there is a tie for last placed element  
    rows <- nrow(healthout)
    
    # Allow "best" and "worst" to signify the first and last ranked hospitals
    if (num == "best"){
        num <- 1  
    }
    else if (num == "worst"){
        num <- rows 
    }
    else if (num > 0){
        num <- num
    }
    else if (num > rows){
        stop("out of range")
    }
    else {
        stop("out of range")
}
    # Order rate 
    # Current one  
    healthout <- healthout[order(healthout[, outcome], healthout[, 1]), ]    
    
    # Add rank number 
    healthout$nums <- seq.int(nrow(healthout)) 
        
    # Print the requested rank - E.g. 
    healthout[healthout[ ,3] == num, ] 
}
```    


# 4. Ranking hospitals in all states 

Write a function called rankall that takes two arguments: an outcome name (outcome) and a hospital ranking (num). The function reads the outcome-of-care-measures.csv file and returns a 2-column data frame
containing the hospital in each state that has the ranking specified in num. For example the function call rankall("heart attack", "best") would return a data frame containing the names of the hospitals that are the best in their respective states for 30-day heart attack death rates. The function should return a value for every state (some may be NA). The first column in the data frame is named hospital, which contains the hospital name, and the second column is named state, which contains the 2-character abbreviation for
the state name. Hospitals that do not have data on a particular outcome should be excluded from the set of hospitals when deciding the rankings.   


## Sample play code 

Ranking by group using dyplyr 


```
data %>% arrange(state, morality) %>% group_by(state) %>% mutate(rank = rank(morality, ties.method = 'first'))
``` 





``` 
rankall <- function(outcome, num = ...){
    
    # Load all information into the data frame
    
    outcomes <- read.csv("outcome-of-care-measures.csv", colClasses =                      "character", na.string = "Not Available")[, c(2,7,11,17,23)]  
    # Change column names 
    colnames(outcomes) <- c("Hospital-Name", "State", "heart attack",                         "heart failure", "pneumonia")    
    
        
    ## Make list of unique state values 
    uniquestate <- as.list(unique(outcomes$State))
    
    ## Check that state and outcome are valid 
    if (state %in% uniquestate){
        paste("proceed")
    }  
    else {
    stop("invalid state") # cancel execution and print error message
    }  

    if (! outcome == "heart attack" || outcome == "pneumonia" || outcome = 
        "heart failure"){ stop("invalid outcome")
    }

    # Subset dataset from provided outcome 
    healthout <- subset(outcomes, select = c("Hospital-Name", "State", outcome)) 

    # Remove NA values and then sort and rank 
    healthout <- na.omit(healthout)

    healthout %>% arrange(State, outcome) %>% group_by(State) %>% mutate(rank = rank(outcome, ties.method = 'first'))  

    
    # unique on rate - the last value will by default by the first duplicate if     # there is a tie for last placed element  
    rows <- nrow(healthout)
    
    # Allow "best" and "worst" to signify the first and last ranked hospitals
    if (num == "best"){
        num <- 1  
    }
    else if (num == "worst"){
        num <- rows 
    }
    else if (num > 0){
        num <- num
    }
    else if (num > rows){
        stop("out of range")
    }
    else {
        stop("out of range")
}
    # Order rate 
    # Current one  
    healthout <- healthout[order(healthout[, outcome], healthout[, 1]), ]    
    
    # Add rank number 
    healthout$nums <- seq.int(nrow(healthout)) 
        
    # Print the requested rank - E.g. 
    healthout[healthout[ ,3] == num, ] 
}








