---
title: "Week-3-Peer-Grade-Assignment"
author: "Dean Basic"
date: "2022-09-01"
output: html_document
---

# Week 3 Assignment - Matrix Inversion and Cache-ing 

Matrix inversion is usually a costly computation and there may be some benefit to caching the inverse of a matrix rather than computing it
repeatedly (there are also alternatives to matrix inversion that we will
not discuss here). Your assignment is to write a pair of functions that
cache the inverse of a matrix.

Write the following functions:

1. `makeCacheMatrix`: This function creates a special "matrix" object that can 
cache its inverse.

Computing the inverse of a square matrix can be done with the `solve` function 
in R. For example, if `X` is a square invertible matrix, then `solve(X)` returns 
its inverse.


1. In pseudocode, let's breakdown what needs to happen
a) Set the matrix as empty (or set the inverse as an empty matrix)
b) calculate the inverse of the matrix 
c) cache the inverse of the matrix 
d) put the inverse of the matrix into cache 

# Part 1 

The function, which creates a matrix that can cache it's inverse will proceed
in the following order; it will set an empty object(matrix), cache this 
object, using an anonymous function it will set the inverse of the object, 
then get the inverse.  

```   
makeCacheMatrix <- function(x = matrix()){
  inv <- NULL # Set as an empty vector
  set <- function(q) { 
    x <<- q # Use scoping operators for cache function
    inv <<- NULL # Cache empty vector
  }
  get <- function() x # Anonymous function within function 
  setInverse <- function(inverse) inv <<- inverse # Set the inverse 
  getInverse <- function() inv # Get the inverse
  list(set = set, get = get, # Form them into a list that can be called
       setInverse = setInverse,
       getInverse = getInverse)
}
```   


# Part 2

`cacheSolve`: This function computes the inverse of the special
"matrix" returned by `makeCacheMatrix` above. If the inverse has
already been calculated (and the matrix has not changed), then
`cacheSolve` should retrieve the inverse from the cache.  

In pseudocode we can breakdown the operations of the function

1. Check whether a matrix cache from above has been created 
2. Retrieve this cache if it has been created
3. Else calculate the inverse of the matrix
4. Then put this inverse into the cache s


This function will call the function above and check whether the inverse
of the matrix has been cached; if it has not, it will proceed to calculate
the inverse, cache, and subsequently print it.   

```   
cacheSolve <- function(x,...) {
  inv <- x$getInverse() # Call x from the function defined above
  if(!is.null(inv)) { # if it isn't empty, return the inverse value
    message("Returning the cached data")
    return(inv)
  }
  data <- x$get() # call the get function 
  inv <- solve(data, ...)  # Calculate the inverse 
  x$setInverse(inv) # Set the inverse and cache it
  inv # Print the inverse of the matrix 
}
```   
















